#################################################################
## ___  ____ _         _       _  ______ _      _   _          ##
## |  \/  (_) |       | |     (_) | ___ (_)    | | | |         ##
## | .  . |_| | _____ | | __ _ _  | |_/ /_  ___| |_| | ____ _  ##
## | |\/| | | |/ / _ \| |/ _` | | |  __/| |/ _ \ __| |/ / _` | ##
## | |  | | |   < (_) | | (_| | | | |   | |  __/ |_|   < (_| | ##
## \_|  |_/_|_|\_\___/|_|\__,_| | \_|   |_|\___|\__|_|\_\__,_| ##
##                           _/ |                              ##
##                          |__/                               ##
#################################################################

# Created by Mikolaj Pietka

add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$jobs\
$character\
"""

[directory]
truncation_symbol = ""

[git_branch]
format = "[$symbol]($style)"

[git_status]
style = "bold yellow"

[cmd_duration]
format = "祥 [$duration]($style)"

[character] 
success_symbol = "[>](bold green)"
error_symbol = "[✗](bold red)"
